[package]
name = "SuiUtils"
version = "0.7.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
sui_utils =  "0xea36816f5d94a60ce84ac1ad85d069dcba7deb17"